### ISSUE TITLE
App doesn't recognise chapo.chat username and password, lemmygrad website does.

### ISSUE THREAD

**Issue by johnledezma34** [krawieck/lemmur#169] opened 2021-02-24 15:12 UTC
Does this have to do with Chapo.chat's use of the old API? Whenever I try and login to lemmur using my Lemmy account, I made over at Chapo. Chat I get an API error for an incorrect username or email. I can correctly login using the lemmygrad. Ml website. Am I doing something wrong, or is it the app?

![Screenshot_20210224-090912](https://user-images.githubusercontent.com/15113074/109021224-4f1b1b00-7680-11eb-823f-3fa73efeeccb.png)

**Comment by shilangyu** [comment] 2021-02-24 15:25
It's not you, not lemmur, it's chapo.chat. 

duplicate of #114

As you said, they are still using the old API which was completely removed and not used by virtually any other lemmy instance

**Closed by shilangyu** 2021-02-24 15:25 UTC

**Comment by johnledezma34** [comment] 2021-02-24 15:26
> 
> 
> It's not you, not lemmur, it's chapo.chat.
> 
> duplicate of #114
> 
> As you said, they are still using the old API which was completely removed and not used by virtually any other lemmy instance

Thanks that's what I figured. :( Thanks for the quick reply.
