### ISSUE TITLE
Android 11 external links not opening

### ISSUE THREAD

**Issue by cambria-dev** [krawieck/lemmur#165] opened 2021-02-19 16:17 UTC
### Device info

- OS: Android
- OS version: 11
- Device: Pixel 4a5g

### Describe the bug
On Android 11, any external links which should open in a browser do not do anything. On Android 10 (LineageOS 17) they are working as intended. 

### Steps to reproduce
Links in posts, "open in browser", source code, and support developer all fail to do anything when clicked.

### Expected behavior
Browser intent should open when clicking any of these links. 

### Additional context
Willing to help by testing builds on an android 11 device if needed.

**Comment by cambria-dev** [comment] 2021-02-19 16:22
Just saw: https://github.com/krawieck/lemmur/commit/93ac19a06fa636719d77c0faac4c27c635363f63

I will build and test later and close this bug report. Currently not working on Lemmur v 0.2.3 from F-Droid.

**Comment by shilangyu** [comment] 2021-02-19 16:47
This was fixed ([see mention in the changelog](https://github.com/krawieck/lemmur/blob/e49cfa221f713aa282257f5968f094ef7d8e368b/CHANGELOG.md#L10)) just not released yet

Duplicate of https://github.com/krawieck/lemmur/issues/138

**Closed by shilangyu** 2021-02-19 16:47 UTC
Labels: bug
