### ISSUE TITLE
Can't subscribe to remote community

### ISSUE THREAD

**Issue by z3dd1cu55** [krawieck/lemmur#230] opened 2021-06-23 13:15 UTC
### Device info

- OS: Android
- OS version: LOS 17 (Android 10)
- Device: Moto G5
- Lemmur version: 0.5.0

### Describe the bug

I cannot subscribe to communities on lemmy.ml when logged in to an account on another instance.

### Steps to reproduce

Be logged in to another instance than lemmy.ml.

1. Hit the search button
2. Enter anything and hit enter
3. Leave the combobox at lemmy.ml (I'm on another instance)
4. Hit search
5. Click on the community-logo of any upcoming post
6. Hit "subscribe" -> `you have to be logged in to do that - log in`

### Expected behavior

I should have subscribed to the community as I am already logged in.

### Screenshots/Screencasts

-

### Additional context

-

### Unrelated

This app is great. Thank you very much!

**Comment by krawieck** [comment] 2021-06-24 07:15
Duplicate of #153

**Closed** 2021-08-15 13:05 UTC
Labels: bug
