### ISSUE TITLE
Don't discard comment/post draft immediately on exit

### ISSUE THREAD

**Issue by iaeerfung** [krawieck/lemmur#288] opened 2021-11-05 11:21 UTC
Too easy to loose comment from a single accidential tap of "Back" button. 
Sometimes I want to read others comments during writhing mine, but can't  without loosing it.
Please make a popup for (not-)saving draft on exit, and option to disable it by always going with desired action.

**Comment by shilangyu** [comment] 2021-11-05 12:32
Duplicate of #255, please check the linked issue where we plan to implement drafts

**Closed** 2021-11-05 12:32 UTC
Labels: enhancement
